version: 0.0  # Correct version format
os: linux  

files:
  - source: .  # Copies only the necessary files
    destination: /var/www/html  

hooks:
  AfterInstall:
    - location: scripts/install_nginx.sh  
      timeout: 300  
      runas: root  

  ApplicationStart:
    - location: scripts/start_nginx.sh  
      timeout: 300  
      runas: root  
